# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackTheNorth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackTheNorth
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Realm'
	pod 'RealmSwift'
	pod 'APIKit'
	pod 'FontAwesomeKit'
	pod 'Material'
	pod 'ObjectMapper'
	pod 'iTunesSearchAPI'
	pod 'Kingfisher', '~> 3.9'
	pod 'Player', '~> 0.7.0'
	pod 'Alamofire', '~> 4.5'
	pod 'SCLAlertView'
	pod 'BMPlayer', '~> 0.9.1'

  target 'HackTheNorthTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackTheNorthUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
